2024-09-19 20:06:59.217 +05:00 [ERR] An unhandled exception occurred while processing the request.
System.InvalidOperationException: Sample Exception
   at Program.<>c.<<Main>$>b__0_1() in /Users/Projects/Projects/Upwork/Spencer Thomason/Youtube/StartupHakkSamples/229_AspNetCore_MIddleware/Middleware/Program.cs:line 39
   at lambda_method5(Closure, Object, HttpContext)
   at Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware.Invoke(HttpContext context)
   at Middleware.Middlewares.GlobalExceptionHandlerMiddleware.InvokeAsync(HttpContext context) in /Users/Projects/Projects/Upwork/Spencer Thomason/Youtube/StartupHakkSamples/229_AspNetCore_MIddleware/Middleware/Middlewares/GlobalExceptionHandlerMiddleware.cs:line 23
2024-09-19 20:06:59.278 +05:00 [ERR] An unhandled exception occurred while processing the request.
System.InvalidOperationException: Sample Exception
   at Program.<>c.<<Main>$>b__0_1() in /Users/Projects/Projects/Upwork/Spencer Thomason/Youtube/StartupHakkSamples/229_AspNetCore_MIddleware/Middleware/Program.cs:line 39
   at lambda_method5(Closure, Object, HttpContext)
   at Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware.Invoke(HttpContext context)
   at Middleware.Middlewares.GlobalExceptionHandlerMiddleware.InvokeAsync(HttpContext context) in /Users/Projects/Projects/Upwork/Spencer Thomason/Youtube/StartupHakkSamples/229_AspNetCore_MIddleware/Middleware/Middlewares/GlobalExceptionHandlerMiddleware.cs:line 23
2024-09-19 20:07:08.140 +05:00 [ERR] An unhandled exception occurred while processing the request.
System.InvalidOperationException: Sample Exception
   at Program.<>c.<<Main>$>b__0_1() in /Users/Projects/Projects/Upwork/Spencer Thomason/Youtube/StartupHakkSamples/229_AspNetCore_MIddleware/Middleware/Program.cs:line 39
   at lambda_method5(Closure, Object, HttpContext)
   at Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware.Invoke(HttpContext context)
   at Middleware.Middlewares.GlobalExceptionHandlerMiddleware.InvokeAsync(HttpContext context) in /Users/Projects/Projects/Upwork/Spencer Thomason/Youtube/StartupHakkSamples/229_AspNetCore_MIddleware/Middleware/Middlewares/GlobalExceptionHandlerMiddleware.cs:line 23
2024-09-19 20:07:08.141 +05:00 [ERR] An unhandled exception occurred while processing the request.
System.InvalidOperationException: Sample Exception
   at Program.<>c.<<Main>$>b__0_1() in /Users/Projects/Projects/Upwork/Spencer Thomason/Youtube/StartupHakkSamples/229_AspNetCore_MIddleware/Middleware/Program.cs:line 39
   at lambda_method5(Closure, Object, HttpContext)
   at Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware.Invoke(HttpContext context)
   at Middleware.Middlewares.GlobalExceptionHandlerMiddleware.InvokeAsync(HttpContext context) in /Users/Projects/Projects/Upwork/Spencer Thomason/Youtube/StartupHakkSamples/229_AspNetCore_MIddleware/Middleware/Middlewares/GlobalExceptionHandlerMiddleware.cs:line 23
2024-09-19 20:08:37.487 +05:00 [ERR] An unhandled exception occurred while processing the request.
System.InvalidOperationException: Sample Exception
   at Middleware.Controllers.ValueController.fetchUsers() in /Users/Projects/Projects/Upwork/Spencer Thomason/Youtube/StartupHakkSamples/229_AspNetCore_MIddleware/Middleware/Controllers/ValueController.cs:line 12
   at lambda_method2(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Middleware.Middlewares.GlobalExceptionHandlerMiddleware.InvokeAsync(HttpContext context) in /Users/Projects/Projects/Upwork/Spencer Thomason/Youtube/StartupHakkSamples/229_AspNetCore_MIddleware/Middleware/Middlewares/GlobalExceptionHandlerMiddleware.cs:line 23
2024-09-19 20:08:37.505 +05:00 [ERR] An unhandled exception occurred while processing the request.
System.InvalidOperationException: Sample Exception
   at Middleware.Controllers.ValueController.fetchUsers() in /Users/Projects/Projects/Upwork/Spencer Thomason/Youtube/StartupHakkSamples/229_AspNetCore_MIddleware/Middleware/Controllers/ValueController.cs:line 12
   at lambda_method2(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Middleware.Middlewares.GlobalExceptionHandlerMiddleware.InvokeAsync(HttpContext context) in /Users/Projects/Projects/Upwork/Spencer Thomason/Youtube/StartupHakkSamples/229_AspNetCore_MIddleware/Middleware/Middlewares/GlobalExceptionHandlerMiddleware.cs:line 23
2024-09-19 20:09:01.725 +05:00 [ERR] An unhandled exception occurred while processing the request.
System.InvalidOperationException: Sample Exception
   at Middleware.Controllers.ValueController.fetchUsers() in /Users/Projects/Projects/Upwork/Spencer Thomason/Youtube/StartupHakkSamples/229_AspNetCore_MIddleware/Middleware/Controllers/ValueController.cs:line 12
   at lambda_method2(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Middleware.Middlewares.GlobalExceptionHandlerMiddleware.InvokeAsync(HttpContext context) in /Users/Projects/Projects/Upwork/Spencer Thomason/Youtube/StartupHakkSamples/229_AspNetCore_MIddleware/Middleware/Middlewares/GlobalExceptionHandlerMiddleware.cs:line 23
2024-09-19 20:09:01.727 +05:00 [ERR] An unhandled exception occurred while processing the request.
System.InvalidOperationException: Sample Exception
   at Middleware.Controllers.ValueController.fetchUsers() in /Users/Projects/Projects/Upwork/Spencer Thomason/Youtube/StartupHakkSamples/229_AspNetCore_MIddleware/Middleware/Controllers/ValueController.cs:line 12
   at lambda_method2(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Middleware.Middlewares.GlobalExceptionHandlerMiddleware.InvokeAsync(HttpContext context) in /Users/Projects/Projects/Upwork/Spencer Thomason/Youtube/StartupHakkSamples/229_AspNetCore_MIddleware/Middleware/Middlewares/GlobalExceptionHandlerMiddleware.cs:line 23
2024-09-19 20:10:10.253 +05:00 [ERR] An unhandled exception occurred while processing the request.
System.InvalidOperationException: Sample Exception
   at Middleware.Controllers.ValueController.fetchUsers() in /Users/Projects/Projects/Upwork/Spencer Thomason/Youtube/StartupHakkSamples/229_AspNetCore_MIddleware/Middleware/Controllers/ValueController.cs:line 12
   at lambda_method2(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Middleware.Middlewares.GlobalExceptionHandlerMiddleware.InvokeAsync(HttpContext context) in /Users/Projects/Projects/Upwork/Spencer Thomason/Youtube/StartupHakkSamples/229_AspNetCore_MIddleware/Middleware/Middlewares/GlobalExceptionHandlerMiddleware.cs:line 23
2024-09-19 20:10:10.271 +05:00 [ERR] An unhandled exception occurred while processing the request.
System.InvalidOperationException: Sample Exception
   at Middleware.Controllers.ValueController.fetchUsers() in /Users/Projects/Projects/Upwork/Spencer Thomason/Youtube/StartupHakkSamples/229_AspNetCore_MIddleware/Middleware/Controllers/ValueController.cs:line 12
   at lambda_method2(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Middleware.Middlewares.GlobalExceptionHandlerMiddleware.InvokeAsync(HttpContext context) in /Users/Projects/Projects/Upwork/Spencer Thomason/Youtube/StartupHakkSamples/229_AspNetCore_MIddleware/Middleware/Middlewares/GlobalExceptionHandlerMiddleware.cs:line 23
2024-09-30 13:49:13.293 -04:00 [ERR] An unhandled exception occurred while processing the request.
System.InvalidOperationException: Sample Exception
   at Middleware.Controllers.ValueController.fetchUsers() in D:\D\Work\StartupHakkSamples\229_AspNetCore_MIddleware\Middleware\Middleware\Controllers\ValueController.cs:line 12
   at lambda_method2(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Middleware.Middlewares.GlobalExceptionHandlerMiddleware.InvokeAsync(HttpContext context) in D:\D\Work\StartupHakkSamples\229_AspNetCore_MIddleware\Middleware\Middleware\Middlewares\GlobalExceptionHandlerMiddleware.cs:line 23
2024-09-30 13:49:13.421 -04:00 [ERR] An unhandled exception occurred while processing the request.
System.InvalidOperationException: Sample Exception
   at Middleware.Controllers.ValueController.fetchUsers() in D:\D\Work\StartupHakkSamples\229_AspNetCore_MIddleware\Middleware\Middleware\Controllers\ValueController.cs:line 12
   at lambda_method2(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Middleware.Middlewares.GlobalExceptionHandlerMiddleware.InvokeAsync(HttpContext context) in D:\D\Work\StartupHakkSamples\229_AspNetCore_MIddleware\Middleware\Middleware\Middlewares\GlobalExceptionHandlerMiddleware.cs:line 23
